local t={
  ImGuizmo_AllowAxisFlip={
    [1]={
      args="(bool value)",
      argsT={
        [1]={
          name="value",
          type="bool"}},
      argsoriginal="(bool value)",
      call_args="(value)",
      cimguiname="ImGuizmo_AllowAxisFlip",
      defaults={},
      funcname="AllowAxisFlip",
      location="ImGuizmo:212",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_AllowAxisFlip",
      ret="void",
      signature="(bool)",
      stname=""},
    ["(bool)"]=nil},
  ImGuizmo_BeginFrame={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImGuizmo_BeginFrame",
      defaults={},
      funcname="BeginFrame",
      location="ImGuizmo:121",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_BeginFrame",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImGuizmo_DecomposeMatrixToComponents={
    [1]={
      args="(const float* matrix,float* translation,float* rotation,float* scale)",
      argsT={
        [1]={
          name="matrix",
          type="const float*"},
        [2]={
          name="translation",
          type="float*"},
        [3]={
          name="rotation",
          type="float*"},
        [4]={
          name="scale",
          type="float*"}},
      argsoriginal="(const float* matrix,float* translation,float* rotation,float* scale)",
      call_args="(matrix,translation,rotation,scale)",
      cimguiname="ImGuizmo_DecomposeMatrixToComponents",
      defaults={},
      funcname="DecomposeMatrixToComponents",
      location="ImGuizmo:151",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_DecomposeMatrixToComponents",
      ret="void",
      signature="(const float*,float*,float*,float*)",
      stname=""},
    ["(const float*,float*,float*,float*)"]=nil},
  ImGuizmo_DrawCubes={
    [1]={
      args="(const float* view,const float* projection,const float* matrices,int matrixCount)",
      argsT={
        [1]={
          name="view",
          type="const float*"},
        [2]={
          name="projection",
          type="const float*"},
        [3]={
          name="matrices",
          type="const float*"},
        [4]={
          name="matrixCount",
          type="int"}},
      argsoriginal="(const float* view,const float* projection,const float* matrices,int matrixCount)",
      call_args="(view,projection,matrices,matrixCount)",
      cimguiname="ImGuizmo_DrawCubes",
      defaults={},
      funcname="DrawCubes",
      location="ImGuizmo:159",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_DrawCubes",
      ret="void",
      signature="(const float*,const float*,const float*,int)",
      stname=""},
    ["(const float*,const float*,const float*,int)"]=nil},
  ImGuizmo_DrawGrid={
    [1]={
      args="(const float* view,const float* projection,const float* matrix,const float gridSize)",
      argsT={
        [1]={
          name="view",
          type="const float*"},
        [2]={
          name="projection",
          type="const float*"},
        [3]={
          name="matrix",
          type="const float*"},
        [4]={
          name="gridSize",
          type="const float"}},
      argsoriginal="(const float* view,const float* projection,const float* matrix,const float gridSize)",
      call_args="(view,projection,matrix,gridSize)",
      cimguiname="ImGuizmo_DrawGrid",
      defaults={},
      funcname="DrawGrid",
      location="ImGuizmo:160",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_DrawGrid",
      ret="void",
      signature="(const float*,const float*,const float*,const float)",
      stname=""},
    ["(const float*,const float*,const float*,const float)"]=nil},
  ImGuizmo_Enable={
    [1]={
      args="(bool enable)",
      argsT={
        [1]={
          name="enable",
          type="bool"}},
      argsoriginal="(bool enable)",
      call_args="(enable)",
      cimguiname="ImGuizmo_Enable",
      defaults={},
      funcname="Enable",
      location="ImGuizmo:137",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_Enable",
      ret="void",
      signature="(bool)",
      stname=""},
    ["(bool)"]=nil},
  ImGuizmo_IsOver={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImGuizmo_IsOver",
      defaults={},
      funcname="IsOver",
      location="ImGuizmo:130",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_IsOver_Nil",
      ret="bool",
      signature="()",
      stname=""},
    [2]={
      args="(OPERATION op)",
      argsT={
        [1]={
          name="op",
          type="OPERATION"}},
      argsoriginal="(OPERATION op)",
      call_args="(op)",
      cimguiname="ImGuizmo_IsOver",
      defaults={},
      funcname="IsOver",
      location="ImGuizmo:206",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_IsOver_OPERATION",
      ret="bool",
      signature="(OPERATION)",
      stname=""},
    ["()"]=nil,
    ["(OPERATION)"]=nil},
  ImGuizmo_IsUsing={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImGuizmo_IsUsing",
      defaults={},
      funcname="IsUsing",
      location="ImGuizmo:133",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_IsUsing",
      ret="bool",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImGuizmo_Manipulate={
    [1]={
      args="(const float* view,const float* projection,OPERATION operation,MODE mode,float* matrix,float* deltaMatrix,const float* snap,const float* localBounds,const float* boundsSnap)",
      argsT={
        [1]={
          name="view",
          type="const float*"},
        [2]={
          name="projection",
          type="const float*"},
        [3]={
          name="operation",
          type="OPERATION"},
        [4]={
          name="mode",
          type="MODE"},
        [5]={
          name="matrix",
          type="float*"},
        [6]={
          name="deltaMatrix",
          type="float*"},
        [7]={
          name="snap",
          type="const float*"},
        [8]={
          name="localBounds",
          type="const float*"},
        [9]={
          name="boundsSnap",
          type="const float*"}},
      argsoriginal="(const float* view,const float* projection,OPERATION operation,MODE mode,float* matrix,float* deltaMatrix=NULL,const float* snap=NULL,const float* localBounds=NULL,const float* boundsSnap=NULL)",
      call_args="(view,projection,operation,mode,matrix,deltaMatrix,snap,localBounds,boundsSnap)",
      cimguiname="ImGuizmo_Manipulate",
      defaults={
        boundsSnap="NULL",
        deltaMatrix="NULL",
        localBounds="NULL",
        snap="NULL"},
      funcname="Manipulate",
      location="ImGuizmo:195",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_Manipulate",
      ret="bool",
      signature="(const float*,const float*,OPERATION,MODE,float*,float*,const float*,const float*,const float*)",
      stname=""},
    ["(const float*,const float*,OPERATION,MODE,float*,float*,const float*,const float*,const float*)"]=nil},
  ImGuizmo_RecomposeMatrixFromComponents={
    [1]={
      args="(const float* translation,const float* rotation,const float* scale,float* matrix)",
      argsT={
        [1]={
          name="translation",
          type="const float*"},
        [2]={
          name="rotation",
          type="const float*"},
        [3]={
          name="scale",
          type="const float*"},
        [4]={
          name="matrix",
          type="float*"}},
      argsoriginal="(const float* translation,const float* rotation,const float* scale,float* matrix)",
      call_args="(translation,rotation,scale,matrix)",
      cimguiname="ImGuizmo_RecomposeMatrixFromComponents",
      defaults={},
      funcname="RecomposeMatrixFromComponents",
      location="ImGuizmo:152",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_RecomposeMatrixFromComponents",
      ret="void",
      signature="(const float*,const float*,const float*,float*)",
      stname=""},
    ["(const float*,const float*,const float*,float*)"]=nil},
  ImGuizmo_SetDrawlist={
    [1]={
      args="(ImDrawList* drawlist)",
      argsT={
        [1]={
          name="drawlist",
          type="ImDrawList*"}},
      argsoriginal="(ImDrawList* drawlist=nullptr)",
      call_args="(drawlist)",
      cimguiname="ImGuizmo_SetDrawlist",
      defaults={
        drawlist="nullptr"},
      funcname="SetDrawlist",
      location="ImGuizmo:118",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_SetDrawlist",
      ret="void",
      signature="(ImDrawList*)",
      stname=""},
    ["(ImDrawList*)"]=nil},
  ImGuizmo_SetGizmoSizeClipSpace={
    [1]={
      args="(float value)",
      argsT={
        [1]={
          name="value",
          type="float"}},
      argsoriginal="(float value)",
      call_args="(value)",
      cimguiname="ImGuizmo_SetGizmoSizeClipSpace",
      defaults={},
      funcname="SetGizmoSizeClipSpace",
      location="ImGuizmo:207",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_SetGizmoSizeClipSpace",
      ret="void",
      signature="(float)",
      stname=""},
    ["(float)"]=nil},
  ImGuizmo_SetID={
    [1]={
      args="(int id)",
      argsT={
        [1]={
          name="id",
          type="int"}},
      argsoriginal="(int id)",
      call_args="(id)",
      cimguiname="ImGuizmo_SetID",
      defaults={},
      funcname="SetID",
      location="ImGuizmo:203",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_SetID",
      ret="void",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImGuizmo_SetImGuiContext={
    [1]={
      args="(ImGuiContext* ctx)",
      argsT={
        [1]={
          name="ctx",
          type="ImGuiContext*"}},
      argsoriginal="(ImGuiContext* ctx)",
      call_args="(ctx)",
      cimguiname="ImGuizmo_SetImGuiContext",
      defaults={},
      funcname="SetImGuiContext",
      location="ImGuizmo:127",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_SetImGuiContext",
      ret="void",
      signature="(ImGuiContext*)",
      stname=""},
    ["(ImGuiContext*)"]=nil},
  ImGuizmo_SetOrthographic={
    [1]={
      args="(bool isOrthographic)",
      argsT={
        [1]={
          name="isOrthographic",
          type="bool"}},
      argsoriginal="(bool isOrthographic)",
      call_args="(isOrthographic)",
      cimguiname="ImGuizmo_SetOrthographic",
      defaults={},
      funcname="SetOrthographic",
      location="ImGuizmo:156",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_SetOrthographic",
      ret="void",
      signature="(bool)",
      stname=""},
    ["(bool)"]=nil},
  ImGuizmo_SetRect={
    [1]={
      args="(float x,float y,float width,float height)",
      argsT={
        [1]={
          name="x",
          type="float"},
        [2]={
          name="y",
          type="float"},
        [3]={
          name="width",
          type="float"},
        [4]={
          name="height",
          type="float"}},
      argsoriginal="(float x,float y,float width,float height)",
      call_args="(x,y,width,height)",
      cimguiname="ImGuizmo_SetRect",
      defaults={},
      funcname="SetRect",
      location="ImGuizmo:154",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_SetRect",
      ret="void",
      signature="(float,float,float,float)",
      stname=""},
    ["(float,float,float,float)"]=nil},
  ImGuizmo_ViewManipulate={
    [1]={
      args="(float* view,float length,ImVec2 position,ImVec2 size,ImU32 backgroundColor)",
      argsT={
        [1]={
          name="view",
          type="float*"},
        [2]={
          name="length",
          type="float"},
        [3]={
          name="position",
          type="ImVec2"},
        [4]={
          name="size",
          type="ImVec2"},
        [5]={
          name="backgroundColor",
          type="ImU32"}},
      argsoriginal="(float* view,float length,ImVec2 position,ImVec2 size,ImU32 backgroundColor)",
      call_args="(view,length,position,size,backgroundColor)",
      cimguiname="ImGuizmo_ViewManipulate",
      defaults={},
      funcname="ViewManipulate",
      location="ImGuizmo:201",
      namespace="ImGuizmo",
      ov_cimguiname="ImGuizmo_ViewManipulate",
      ret="void",
      signature="(float*,float,ImVec2,ImVec2,ImU32)",
      stname=""},
    ["(float*,float,ImVec2,ImVec2,ImU32)"]=nil}}
t.ImGuizmo_AllowAxisFlip["(bool)"]=t.ImGuizmo_AllowAxisFlip[1]
t.ImGuizmo_BeginFrame["()"]=t.ImGuizmo_BeginFrame[1]
t.ImGuizmo_DecomposeMatrixToComponents["(const float*,float*,float*,float*)"]=t.ImGuizmo_DecomposeMatrixToComponents[1]
t.ImGuizmo_DrawCubes["(const float*,const float*,const float*,int)"]=t.ImGuizmo_DrawCubes[1]
t.ImGuizmo_DrawGrid["(const float*,const float*,const float*,const float)"]=t.ImGuizmo_DrawGrid[1]
t.ImGuizmo_Enable["(bool)"]=t.ImGuizmo_Enable[1]
t.ImGuizmo_IsOver["()"]=t.ImGuizmo_IsOver[1]
t.ImGuizmo_IsOver["(OPERATION)"]=t.ImGuizmo_IsOver[2]
t.ImGuizmo_IsUsing["()"]=t.ImGuizmo_IsUsing[1]
t.ImGuizmo_Manipulate["(const float*,const float*,OPERATION,MODE,float*,float*,const float*,const float*,const float*)"]=t.ImGuizmo_Manipulate[1]
t.ImGuizmo_RecomposeMatrixFromComponents["(const float*,const float*,const float*,float*)"]=t.ImGuizmo_RecomposeMatrixFromComponents[1]
t.ImGuizmo_SetDrawlist["(ImDrawList*)"]=t.ImGuizmo_SetDrawlist[1]
t.ImGuizmo_SetGizmoSizeClipSpace["(float)"]=t.ImGuizmo_SetGizmoSizeClipSpace[1]
t.ImGuizmo_SetID["(int)"]=t.ImGuizmo_SetID[1]
t.ImGuizmo_SetImGuiContext["(ImGuiContext*)"]=t.ImGuizmo_SetImGuiContext[1]
t.ImGuizmo_SetOrthographic["(bool)"]=t.ImGuizmo_SetOrthographic[1]
t.ImGuizmo_SetRect["(float,float,float,float)"]=t.ImGuizmo_SetRect[1]
t.ImGuizmo_ViewManipulate["(float*,float,ImVec2,ImVec2,ImU32)"]=t.ImGuizmo_ViewManipulate[1]
 return t