local t={
  EmulateThreeButtonMouse_EmulateThreeButtonMouse={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="EmulateThreeButtonMouse_EmulateThreeButtonMouse",
      constructor=true,
      defaults={},
      funcname="EmulateThreeButtonMouse",
      location="imnodes:98",
      ov_cimguiname="EmulateThreeButtonMouse_EmulateThreeButtonMouse",
      signature="()",
      stname="EmulateThreeButtonMouse"},
    ["()"]=nil},
  EmulateThreeButtonMouse_destroy={
    [1]={
      args="(EmulateThreeButtonMouse* self)",
      argsT={
        [1]={
          name="self",
          type="EmulateThreeButtonMouse*"}},
      call_args="(self)",
      cimguiname="EmulateThreeButtonMouse_destroy",
      defaults={},
      destructor=true,
      location="imnodes:98",
      ov_cimguiname="EmulateThreeButtonMouse_destroy",
      ret="void",
      signature="(EmulateThreeButtonMouse*)",
      stname="EmulateThreeButtonMouse"},
    ["(EmulateThreeButtonMouse*)"]=nil},
  ImNodesIO_ImNodesIO={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodesIO_ImNodesIO",
      constructor=true,
      defaults={},
      funcname="ImNodesIO",
      location="imnodes:128",
      ov_cimguiname="ImNodesIO_ImNodesIO",
      signature="()",
      stname="ImNodesIO"},
    ["()"]=nil},
  ImNodesIO_destroy={
    [1]={
      args="(ImNodesIO* self)",
      argsT={
        [1]={
          name="self",
          type="ImNodesIO*"}},
      call_args="(self)",
      cimguiname="ImNodesIO_destroy",
      defaults={},
      destructor=true,
      location="imnodes:128",
      ov_cimguiname="ImNodesIO_destroy",
      ret="void",
      signature="(ImNodesIO*)",
      stname="ImNodesIO"},
    ["(ImNodesIO*)"]=nil},
  ImNodesStyle_ImNodesStyle={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodesStyle_ImNodesStyle",
      constructor=true,
      defaults={},
      funcname="ImNodesStyle",
      location="imnodes:170",
      ov_cimguiname="ImNodesStyle_ImNodesStyle",
      signature="()",
      stname="ImNodesStyle"},
    ["()"]=nil},
  ImNodesStyle_destroy={
    [1]={
      args="(ImNodesStyle* self)",
      argsT={
        [1]={
          name="self",
          type="ImNodesStyle*"}},
      call_args="(self)",
      cimguiname="ImNodesStyle_destroy",
      defaults={},
      destructor=true,
      location="imnodes:170",
      ov_cimguiname="ImNodesStyle_destroy",
      ret="void",
      signature="(ImNodesStyle*)",
      stname="ImNodesStyle"},
    ["(ImNodesStyle*)"]=nil},
  ImNodes_BeginInputAttribute={
    [1]={
      args="(int id,ImNodesPinShape shape)",
      argsT={
        [1]={
          name="id",
          type="int"},
        [2]={
          name="shape",
          type="ImNodesPinShape"}},
      argsoriginal="(int id,ImNodesPinShape shape=ImNodesPinShape_CircleFilled)",
      call_args="(id,shape)",
      cimguiname="ImNodes_BeginInputAttribute",
      defaults={
        shape="ImNodesPinShape_CircleFilled"},
      funcname="BeginInputAttribute",
      location="imnodes:264",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_BeginInputAttribute",
      ret="void",
      signature="(int,ImNodesPinShape)",
      stname=""},
    ["(int,ImNodesPinShape)"]=nil},
  ImNodes_BeginNode={
    [1]={
      args="(int id)",
      argsT={
        [1]={
          name="id",
          type="int"}},
      argsoriginal="(int id)",
      call_args="(id)",
      cimguiname="ImNodes_BeginNode",
      defaults={},
      funcname="BeginNode",
      location="imnodes:243",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_BeginNode",
      ret="void",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_BeginNodeEditor={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_BeginNodeEditor",
      defaults={},
      funcname="BeginNodeEditor",
      location="imnodes:225",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_BeginNodeEditor",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_BeginNodeTitleBar={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_BeginNodeTitleBar",
      defaults={},
      funcname="BeginNodeTitleBar",
      location="imnodes:251",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_BeginNodeTitleBar",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_BeginOutputAttribute={
    [1]={
      args="(int id,ImNodesPinShape shape)",
      argsT={
        [1]={
          name="id",
          type="int"},
        [2]={
          name="shape",
          type="ImNodesPinShape"}},
      argsoriginal="(int id,ImNodesPinShape shape=ImNodesPinShape_CircleFilled)",
      call_args="(id,shape)",
      cimguiname="ImNodes_BeginOutputAttribute",
      defaults={
        shape="ImNodesPinShape_CircleFilled"},
      funcname="BeginOutputAttribute",
      location="imnodes:267",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_BeginOutputAttribute",
      ret="void",
      signature="(int,ImNodesPinShape)",
      stname=""},
    ["(int,ImNodesPinShape)"]=nil},
  ImNodes_BeginStaticAttribute={
    [1]={
      args="(int id)",
      argsT={
        [1]={
          name="id",
          type="int"}},
      argsoriginal="(int id)",
      call_args="(id)",
      cimguiname="ImNodes_BeginStaticAttribute",
      defaults={},
      funcname="BeginStaticAttribute",
      location="imnodes:272",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_BeginStaticAttribute",
      ret="void",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_ClearLinkSelection={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_ClearLinkSelection",
      defaults={},
      funcname="ClearLinkSelection",
      location="imnodes:325",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_ClearLinkSelection_Nil",
      ret="void",
      signature="()",
      stname=""},
    [2]={
      args="(int link_id)",
      argsT={
        [1]={
          name="link_id",
          type="int"}},
      argsoriginal="(int link_id)",
      call_args="(link_id)",
      cimguiname="ImNodes_ClearLinkSelection",
      defaults={},
      funcname="ClearLinkSelection",
      location="imnodes:336",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_ClearLinkSelection_Int",
      ret="void",
      signature="(int)",
      stname=""},
    ["()"]=nil,
    ["(int)"]=nil},
  ImNodes_ClearNodeSelection={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_ClearNodeSelection",
      defaults={},
      funcname="ClearNodeSelection",
      location="imnodes:324",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_ClearNodeSelection_Nil",
      ret="void",
      signature="()",
      stname=""},
    [2]={
      args="(int node_id)",
      argsT={
        [1]={
          name="node_id",
          type="int"}},
      argsoriginal="(int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_ClearNodeSelection",
      defaults={},
      funcname="ClearNodeSelection",
      location="imnodes:333",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_ClearNodeSelection_Int",
      ret="void",
      signature="(int)",
      stname=""},
    ["()"]=nil,
    ["(int)"]=nil},
  ImNodes_CreateContext={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_CreateContext",
      defaults={},
      funcname="CreateContext",
      location="imnodes:202",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_CreateContext",
      ret="ImNodesContext*",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_DestroyContext={
    [1]={
      args="(ImNodesContext* ctx)",
      argsT={
        [1]={
          name="ctx",
          type="ImNodesContext*"}},
      argsoriginal="(ImNodesContext* ctx=((void*)0))",
      call_args="(ctx)",
      cimguiname="ImNodes_DestroyContext",
      defaults={
        ctx="NULL"},
      funcname="DestroyContext",
      location="imnodes:203",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_DestroyContext",
      ret="void",
      signature="(ImNodesContext*)",
      stname=""},
    ["(ImNodesContext*)"]=nil},
  ImNodes_EditorContextCreate={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EditorContextCreate",
      defaults={},
      funcname="EditorContextCreate",
      location="imnodes:207",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EditorContextCreate",
      ret="ImNodesEditorContext*",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EditorContextFree={
    [1]={
      args="(ImNodesEditorContext* noname1)",
      argsT={
        [1]={
          name="noname1",
          type="ImNodesEditorContext*"}},
      argsoriginal="(ImNodesEditorContext*)",
      call_args="(noname1)",
      cimguiname="ImNodes_EditorContextFree",
      defaults={},
      funcname="EditorContextFree",
      location="imnodes:208",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EditorContextFree",
      ret="void",
      signature="(ImNodesEditorContext*)",
      stname=""},
    ["(ImNodesEditorContext*)"]=nil},
  ImNodes_EditorContextGetPanning={
    [1]={
      args="(ImVec2 *pOut)",
      argsT={
        [1]={
          name="pOut",
          type="ImVec2*"}},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EditorContextGetPanning",
      defaults={},
      funcname="EditorContextGetPanning",
      location="imnodes:210",
      namespace="ImNodes",
      nonUDT=1,
      ov_cimguiname="ImNodes_EditorContextGetPanning",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EditorContextMoveToNode={
    [1]={
      args="(const int node_id)",
      argsT={
        [1]={
          name="node_id",
          type="const int"}},
      argsoriginal="(const int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_EditorContextMoveToNode",
      defaults={},
      funcname="EditorContextMoveToNode",
      location="imnodes:212",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EditorContextMoveToNode",
      ret="void",
      signature="(const int)",
      stname=""},
    ["(const int)"]=nil},
  ImNodes_EditorContextResetPanning={
    [1]={
      args="(const ImVec2 pos)",
      argsT={
        [1]={
          name="pos",
          type="const ImVec2"}},
      argsoriginal="(const ImVec2& pos)",
      call_args="(pos)",
      cimguiname="ImNodes_EditorContextResetPanning",
      defaults={},
      funcname="EditorContextResetPanning",
      location="imnodes:211",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EditorContextResetPanning",
      ret="void",
      signature="(const ImVec2)",
      stname=""},
    ["(const ImVec2)"]=nil},
  ImNodes_EditorContextSet={
    [1]={
      args="(ImNodesEditorContext* noname1)",
      argsT={
        [1]={
          name="noname1",
          type="ImNodesEditorContext*"}},
      argsoriginal="(ImNodesEditorContext*)",
      call_args="(noname1)",
      cimguiname="ImNodes_EditorContextSet",
      defaults={},
      funcname="EditorContextSet",
      location="imnodes:209",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EditorContextSet",
      ret="void",
      signature="(ImNodesEditorContext*)",
      stname=""},
    ["(ImNodesEditorContext*)"]=nil},
  ImNodes_EndInputAttribute={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EndInputAttribute",
      defaults={},
      funcname="EndInputAttribute",
      location="imnodes:265",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EndInputAttribute",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EndNode={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EndNode",
      defaults={},
      funcname="EndNode",
      location="imnodes:244",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EndNode",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EndNodeEditor={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EndNodeEditor",
      defaults={},
      funcname="EndNodeEditor",
      location="imnodes:226",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EndNodeEditor",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EndNodeTitleBar={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EndNodeTitleBar",
      defaults={},
      funcname="EndNodeTitleBar",
      location="imnodes:252",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EndNodeTitleBar",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EndOutputAttribute={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EndOutputAttribute",
      defaults={},
      funcname="EndOutputAttribute",
      location="imnodes:268",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EndOutputAttribute",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_EndStaticAttribute={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_EndStaticAttribute",
      defaults={},
      funcname="EndStaticAttribute",
      location="imnodes:273",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_EndStaticAttribute",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_GetCurrentContext={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_GetCurrentContext",
      defaults={},
      funcname="GetCurrentContext",
      location="imnodes:204",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_GetCurrentContext",
      ret="ImNodesContext*",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_GetIO={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_GetIO",
      defaults={},
      funcname="GetIO",
      location="imnodes:214",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_GetIO",
      ret="ImNodesIO*",
      retref="&",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_GetNodeDimensions={
    [1]={
      args="(ImVec2 *pOut,int id)",
      argsT={
        [1]={
          name="pOut",
          type="ImVec2*"},
        [2]={
          name="id",
          type="int"}},
      argsoriginal="(int id)",
      call_args="(id)",
      cimguiname="ImNodes_GetNodeDimensions",
      defaults={},
      funcname="GetNodeDimensions",
      location="imnodes:246",
      namespace="ImNodes",
      nonUDT=1,
      ov_cimguiname="ImNodes_GetNodeDimensions",
      ret="void",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_GetNodeEditorSpacePos={
    [1]={
      args="(ImVec2 *pOut,const int node_id)",
      argsT={
        [1]={
          name="pOut",
          type="ImVec2*"},
        [2]={
          name="node_id",
          type="const int"}},
      argsoriginal="(const int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_GetNodeEditorSpacePos",
      defaults={},
      funcname="GetNodeEditorSpacePos",
      location="imnodes:301",
      namespace="ImNodes",
      nonUDT=1,
      ov_cimguiname="ImNodes_GetNodeEditorSpacePos",
      ret="void",
      signature="(const int)",
      stname=""},
    ["(const int)"]=nil},
  ImNodes_GetNodeGridSpacePos={
    [1]={
      args="(ImVec2 *pOut,const int node_id)",
      argsT={
        [1]={
          name="pOut",
          type="ImVec2*"},
        [2]={
          name="node_id",
          type="const int"}},
      argsoriginal="(const int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_GetNodeGridSpacePos",
      defaults={},
      funcname="GetNodeGridSpacePos",
      location="imnodes:302",
      namespace="ImNodes",
      nonUDT=1,
      ov_cimguiname="ImNodes_GetNodeGridSpacePos",
      ret="void",
      signature="(const int)",
      stname=""},
    ["(const int)"]=nil},
  ImNodes_GetNodeScreenSpacePos={
    [1]={
      args="(ImVec2 *pOut,const int node_id)",
      argsT={
        [1]={
          name="pOut",
          type="ImVec2*"},
        [2]={
          name="node_id",
          type="const int"}},
      argsoriginal="(const int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_GetNodeScreenSpacePos",
      defaults={},
      funcname="GetNodeScreenSpacePos",
      location="imnodes:300",
      namespace="ImNodes",
      nonUDT=1,
      ov_cimguiname="ImNodes_GetNodeScreenSpacePos",
      ret="void",
      signature="(const int)",
      stname=""},
    ["(const int)"]=nil},
  ImNodes_GetSelectedLinks={
    [1]={
      args="(int* link_ids)",
      argsT={
        [1]={
          name="link_ids",
          type="int*"}},
      argsoriginal="(int* link_ids)",
      call_args="(link_ids)",
      cimguiname="ImNodes_GetSelectedLinks",
      defaults={},
      funcname="GetSelectedLinks",
      location="imnodes:322",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_GetSelectedLinks",
      ret="void",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_GetSelectedNodes={
    [1]={
      args="(int* node_ids)",
      argsT={
        [1]={
          name="node_ids",
          type="int*"}},
      argsoriginal="(int* node_ids)",
      call_args="(node_ids)",
      cimguiname="ImNodes_GetSelectedNodes",
      defaults={},
      funcname="GetSelectedNodes",
      location="imnodes:321",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_GetSelectedNodes",
      ret="void",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_GetStyle={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_GetStyle",
      defaults={},
      funcname="GetStyle",
      location="imnodes:217",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_GetStyle",
      ret="ImNodesStyle*",
      retref="&",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_IsAnyAttributeActive={
    [1]={
      args="(int* attribute_id)",
      argsT={
        [1]={
          name="attribute_id",
          type="int*"}},
      argsoriginal="(int* attribute_id=((void*)0))",
      call_args="(attribute_id)",
      cimguiname="ImNodes_IsAnyAttributeActive",
      defaults={
        attribute_id="NULL"},
      funcname="IsAnyAttributeActive",
      location="imnodes:343",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsAnyAttributeActive",
      ret="bool",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_IsAttributeActive={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_IsAttributeActive",
      defaults={},
      funcname="IsAttributeActive",
      location="imnodes:341",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsAttributeActive",
      ret="bool",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_IsEditorHovered={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_IsEditorHovered",
      defaults={},
      funcname="IsEditorHovered",
      location="imnodes:306",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsEditorHovered",
      ret="bool",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_IsLinkCreated={
    [1]={
      args="(int* started_at_attribute_id,int* ended_at_attribute_id,bool* created_from_snap)",
      argsT={
        [1]={
          name="started_at_attribute_id",
          type="int*"},
        [2]={
          name="ended_at_attribute_id",
          type="int*"},
        [3]={
          name="created_from_snap",
          type="bool*"}},
      argsoriginal="(int* started_at_attribute_id,int* ended_at_attribute_id,bool* created_from_snap=((void*)0))",
      call_args="(started_at_attribute_id,ended_at_attribute_id,created_from_snap)",
      cimguiname="ImNodes_IsLinkCreated",
      defaults={
        created_from_snap="NULL"},
      funcname="IsLinkCreated",
      location="imnodes:358",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkCreated_BoolPtr",
      ret="bool",
      signature="(int*,int*,bool*)",
      stname=""},
    [2]={
      args="(int* started_at_node_id,int* started_at_attribute_id,int* ended_at_node_id,int* ended_at_attribute_id,bool* created_from_snap)",
      argsT={
        [1]={
          name="started_at_node_id",
          type="int*"},
        [2]={
          name="started_at_attribute_id",
          type="int*"},
        [3]={
          name="ended_at_node_id",
          type="int*"},
        [4]={
          name="ended_at_attribute_id",
          type="int*"},
        [5]={
          name="created_from_snap",
          type="bool*"}},
      argsoriginal="(int* started_at_node_id,int* started_at_attribute_id,int* ended_at_node_id,int* ended_at_attribute_id,bool* created_from_snap=((void*)0))",
      call_args="(started_at_node_id,started_at_attribute_id,ended_at_node_id,ended_at_attribute_id,created_from_snap)",
      cimguiname="ImNodes_IsLinkCreated",
      defaults={
        created_from_snap="NULL"},
      funcname="IsLinkCreated",
      location="imnodes:362",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkCreated_IntPtr",
      ret="bool",
      signature="(int*,int*,int*,int*,bool*)",
      stname=""},
    ["(int*,int*,bool*)"]=nil,
    ["(int*,int*,int*,int*,bool*)"]=nil},
  ImNodes_IsLinkDestroyed={
    [1]={
      args="(int* link_id)",
      argsT={
        [1]={
          name="link_id",
          type="int*"}},
      argsoriginal="(int* link_id)",
      call_args="(link_id)",
      cimguiname="ImNodes_IsLinkDestroyed",
      defaults={},
      funcname="IsLinkDestroyed",
      location="imnodes:371",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkDestroyed",
      ret="bool",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_IsLinkDropped={
    [1]={
      args="(int* started_at_attribute_id,bool including_detached_links)",
      argsT={
        [1]={
          name="started_at_attribute_id",
          type="int*"},
        [2]={
          name="including_detached_links",
          type="bool"}},
      argsoriginal="(int* started_at_attribute_id=((void*)0),bool including_detached_links=true)",
      call_args="(started_at_attribute_id,including_detached_links)",
      cimguiname="ImNodes_IsLinkDropped",
      defaults={
        including_detached_links="true",
        started_at_attribute_id="NULL"},
      funcname="IsLinkDropped",
      location="imnodes:356",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkDropped",
      ret="bool",
      signature="(int*,bool)",
      stname=""},
    ["(int*,bool)"]=nil},
  ImNodes_IsLinkHovered={
    [1]={
      args="(int* link_id)",
      argsT={
        [1]={
          name="link_id",
          type="int*"}},
      argsoriginal="(int* link_id)",
      call_args="(link_id)",
      cimguiname="ImNodes_IsLinkHovered",
      defaults={},
      funcname="IsLinkHovered",
      location="imnodes:311",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkHovered",
      ret="bool",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_IsLinkSelected={
    [1]={
      args="(int link_id)",
      argsT={
        [1]={
          name="link_id",
          type="int"}},
      argsoriginal="(int link_id)",
      call_args="(link_id)",
      cimguiname="ImNodes_IsLinkSelected",
      defaults={},
      funcname="IsLinkSelected",
      location="imnodes:337",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkSelected",
      ret="bool",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_IsLinkStarted={
    [1]={
      args="(int* started_at_attribute_id)",
      argsT={
        [1]={
          name="started_at_attribute_id",
          type="int*"}},
      argsoriginal="(int* started_at_attribute_id)",
      call_args="(started_at_attribute_id)",
      cimguiname="ImNodes_IsLinkStarted",
      defaults={},
      funcname="IsLinkStarted",
      location="imnodes:349",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsLinkStarted",
      ret="bool",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_IsNodeHovered={
    [1]={
      args="(int* node_id)",
      argsT={
        [1]={
          name="node_id",
          type="int*"}},
      argsoriginal="(int* node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_IsNodeHovered",
      defaults={},
      funcname="IsNodeHovered",
      location="imnodes:310",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsNodeHovered",
      ret="bool",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_IsNodeSelected={
    [1]={
      args="(int node_id)",
      argsT={
        [1]={
          name="node_id",
          type="int"}},
      argsoriginal="(int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_IsNodeSelected",
      defaults={},
      funcname="IsNodeSelected",
      location="imnodes:334",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsNodeSelected",
      ret="bool",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_IsPinHovered={
    [1]={
      args="(int* attribute_id)",
      argsT={
        [1]={
          name="attribute_id",
          type="int*"}},
      argsoriginal="(int* attribute_id)",
      call_args="(attribute_id)",
      cimguiname="ImNodes_IsPinHovered",
      defaults={},
      funcname="IsPinHovered",
      location="imnodes:312",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_IsPinHovered",
      ret="bool",
      signature="(int*)",
      stname=""},
    ["(int*)"]=nil},
  ImNodes_Link={
    [1]={
      args="(int id,int start_attribute_id,int end_attribute_id)",
      argsT={
        [1]={
          name="id",
          type="int"},
        [2]={
          name="start_attribute_id",
          type="int"},
        [3]={
          name="end_attribute_id",
          type="int"}},
      argsoriginal="(int id,int start_attribute_id,int end_attribute_id)",
      call_args="(id,start_attribute_id,end_attribute_id)",
      cimguiname="ImNodes_Link",
      defaults={},
      funcname="Link",
      location="imnodes:282",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_Link",
      ret="void",
      signature="(int,int,int)",
      stname=""},
    ["(int,int,int)"]=nil},
  ImNodes_LoadCurrentEditorStateFromIniFile={
    [1]={
      args="(const char* file_name)",
      argsT={
        [1]={
          name="file_name",
          type="const char*"}},
      argsoriginal="(const char* file_name)",
      call_args="(file_name)",
      cimguiname="ImNodes_LoadCurrentEditorStateFromIniFile",
      defaults={},
      funcname="LoadCurrentEditorStateFromIniFile",
      location="imnodes:387",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_LoadCurrentEditorStateFromIniFile",
      ret="void",
      signature="(const char*)",
      stname=""},
    ["(const char*)"]=nil},
  ImNodes_LoadCurrentEditorStateFromIniString={
    [1]={
      args="(const char* data,size_t data_size)",
      argsT={
        [1]={
          name="data",
          type="const char*"},
        [2]={
          name="data_size",
          type="size_t"}},
      argsoriginal="(const char* data,size_t data_size)",
      call_args="(data,data_size)",
      cimguiname="ImNodes_LoadCurrentEditorStateFromIniString",
      defaults={},
      funcname="LoadCurrentEditorStateFromIniString",
      location="imnodes:381",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_LoadCurrentEditorStateFromIniString",
      ret="void",
      signature="(const char*,size_t)",
      stname=""},
    ["(const char*,size_t)"]=nil},
  ImNodes_LoadEditorStateFromIniFile={
    [1]={
      args="(ImNodesEditorContext* editor,const char* file_name)",
      argsT={
        [1]={
          name="editor",
          type="ImNodesEditorContext*"},
        [2]={
          name="file_name",
          type="const char*"}},
      argsoriginal="(ImNodesEditorContext* editor,const char* file_name)",
      call_args="(editor,file_name)",
      cimguiname="ImNodes_LoadEditorStateFromIniFile",
      defaults={},
      funcname="LoadEditorStateFromIniFile",
      location="imnodes:388",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_LoadEditorStateFromIniFile",
      ret="void",
      signature="(ImNodesEditorContext*,const char*)",
      stname=""},
    ["(ImNodesEditorContext*,const char*)"]=nil},
  ImNodes_LoadEditorStateFromIniString={
    [1]={
      args="(ImNodesEditorContext* editor,const char* data,size_t data_size)",
      argsT={
        [1]={
          name="editor",
          type="ImNodesEditorContext*"},
        [2]={
          name="data",
          type="const char*"},
        [3]={
          name="data_size",
          type="size_t"}},
      argsoriginal="(ImNodesEditorContext* editor,const char* data,size_t data_size)",
      call_args="(editor,data,data_size)",
      cimguiname="ImNodes_LoadEditorStateFromIniString",
      defaults={},
      funcname="LoadEditorStateFromIniString",
      location="imnodes:382",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_LoadEditorStateFromIniString",
      ret="void",
      signature="(ImNodesEditorContext*,const char*,size_t)",
      stname=""},
    ["(ImNodesEditorContext*,const char*,size_t)"]=nil},
  ImNodes_MiniMap={
    [1]={
      args="(const float minimap_size_fraction,const ImNodesMiniMapLocation location,const ImNodesMiniMapNodeHoveringCallback node_hovering_callback,void* node_hovering_callback_data)",
      argsT={
        [1]={
          name="minimap_size_fraction",
          type="const float"},
        [2]={
          name="location",
          type="const ImNodesMiniMapLocation"},
        [3]={
          name="node_hovering_callback",
          type="const ImNodesMiniMapNodeHoveringCallback"},
        [4]={
          name="node_hovering_callback_data",
          type="void*"}},
      argsoriginal="(const float minimap_size_fraction=0.2f,const ImNodesMiniMapLocation location=ImNodesMiniMapLocation_TopLeft,const ImNodesMiniMapNodeHoveringCallback node_hovering_callback=((void*)0),void* node_hovering_callback_data=((void*)0))",
      call_args="(minimap_size_fraction,location,node_hovering_callback,node_hovering_callback_data)",
      cimguiname="ImNodes_MiniMap",
      defaults={
        location="ImNodesMiniMapLocation_TopLeft",
        minimap_size_fraction="0.2f",
        node_hovering_callback="NULL",
        node_hovering_callback_data="NULL"},
      funcname="MiniMap",
      location="imnodes:230",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_MiniMap",
      ret="void",
      signature="(const float,const ImNodesMiniMapLocation,const ImNodesMiniMapNodeHoveringCallback,void*)",
      stname=""},
    ["(const float,const ImNodesMiniMapLocation,const ImNodesMiniMapNodeHoveringCallback,void*)"]=nil},
  ImNodes_NumSelectedLinks={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_NumSelectedLinks",
      defaults={},
      funcname="NumSelectedLinks",
      location="imnodes:317",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_NumSelectedLinks",
      ret="int",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_NumSelectedNodes={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_NumSelectedNodes",
      defaults={},
      funcname="NumSelectedNodes",
      location="imnodes:316",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_NumSelectedNodes",
      ret="int",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_PopAttributeFlag={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_PopAttributeFlag",
      defaults={},
      funcname="PopAttributeFlag",
      location="imnodes:277",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_PopAttributeFlag",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_PopColorStyle={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_PopColorStyle",
      defaults={},
      funcname="PopColorStyle",
      location="imnodes:238",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_PopColorStyle",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_PopStyleVar={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_PopStyleVar",
      defaults={},
      funcname="PopStyleVar",
      location="imnodes:240",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_PopStyleVar",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_PushAttributeFlag={
    [1]={
      args="(ImNodesAttributeFlags flag)",
      argsT={
        [1]={
          name="flag",
          type="ImNodesAttributeFlags"}},
      argsoriginal="(ImNodesAttributeFlags flag)",
      call_args="(flag)",
      cimguiname="ImNodes_PushAttributeFlag",
      defaults={},
      funcname="PushAttributeFlag",
      location="imnodes:276",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_PushAttributeFlag",
      ret="void",
      signature="(ImNodesAttributeFlags)",
      stname=""},
    ["(ImNodesAttributeFlags)"]=nil},
  ImNodes_PushColorStyle={
    [1]={
      args="(ImNodesCol item,unsigned int color)",
      argsT={
        [1]={
          name="item",
          type="ImNodesCol"},
        [2]={
          name="color",
          type="unsigned int"}},
      argsoriginal="(ImNodesCol item,unsigned int color)",
      call_args="(item,color)",
      cimguiname="ImNodes_PushColorStyle",
      defaults={},
      funcname="PushColorStyle",
      location="imnodes:237",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_PushColorStyle",
      ret="void",
      signature="(ImNodesCol,unsigned int)",
      stname=""},
    ["(ImNodesCol,unsigned int)"]=nil},
  ImNodes_PushStyleVar={
    [1]={
      args="(ImNodesStyleVar style_item,float value)",
      argsT={
        [1]={
          name="style_item",
          type="ImNodesStyleVar"},
        [2]={
          name="value",
          type="float"}},
      argsoriginal="(ImNodesStyleVar style_item,float value)",
      call_args="(style_item,value)",
      cimguiname="ImNodes_PushStyleVar",
      defaults={},
      funcname="PushStyleVar",
      location="imnodes:239",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_PushStyleVar",
      ret="void",
      signature="(ImNodesStyleVar,float)",
      stname=""},
    ["(ImNodesStyleVar,float)"]=nil},
  ImNodes_SaveCurrentEditorStateToIniFile={
    [1]={
      args="(const char* file_name)",
      argsT={
        [1]={
          name="file_name",
          type="const char*"}},
      argsoriginal="(const char* file_name)",
      call_args="(file_name)",
      cimguiname="ImNodes_SaveCurrentEditorStateToIniFile",
      defaults={},
      funcname="SaveCurrentEditorStateToIniFile",
      location="imnodes:384",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SaveCurrentEditorStateToIniFile",
      ret="void",
      signature="(const char*)",
      stname=""},
    ["(const char*)"]=nil},
  ImNodes_SaveCurrentEditorStateToIniString={
    [1]={
      args="(size_t* data_size)",
      argsT={
        [1]={
          name="data_size",
          type="size_t*"}},
      argsoriginal="(size_t* data_size=((void*)0))",
      call_args="(data_size)",
      cimguiname="ImNodes_SaveCurrentEditorStateToIniString",
      defaults={
        data_size="NULL"},
      funcname="SaveCurrentEditorStateToIniString",
      location="imnodes:376",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SaveCurrentEditorStateToIniString",
      ret="const char*",
      signature="(size_t*)",
      stname=""},
    ["(size_t*)"]=nil},
  ImNodes_SaveEditorStateToIniFile={
    [1]={
      args="(const ImNodesEditorContext* editor,const char* file_name)",
      argsT={
        [1]={
          name="editor",
          type="const ImNodesEditorContext*"},
        [2]={
          name="file_name",
          type="const char*"}},
      argsoriginal="(const ImNodesEditorContext* editor,const char* file_name)",
      call_args="(editor,file_name)",
      cimguiname="ImNodes_SaveEditorStateToIniFile",
      defaults={},
      funcname="SaveEditorStateToIniFile",
      location="imnodes:385",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SaveEditorStateToIniFile",
      ret="void",
      signature="(const ImNodesEditorContext*,const char*)",
      stname=""},
    ["(const ImNodesEditorContext*,const char*)"]=nil},
  ImNodes_SaveEditorStateToIniString={
    [1]={
      args="(const ImNodesEditorContext* editor,size_t* data_size)",
      argsT={
        [1]={
          name="editor",
          type="const ImNodesEditorContext*"},
        [2]={
          name="data_size",
          type="size_t*"}},
      argsoriginal="(const ImNodesEditorContext* editor,size_t* data_size=((void*)0))",
      call_args="(editor,data_size)",
      cimguiname="ImNodes_SaveEditorStateToIniString",
      defaults={
        data_size="NULL"},
      funcname="SaveEditorStateToIniString",
      location="imnodes:377",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SaveEditorStateToIniString",
      ret="const char*",
      signature="(const ImNodesEditorContext*,size_t*)",
      stname=""},
    ["(const ImNodesEditorContext*,size_t*)"]=nil},
  ImNodes_SelectLink={
    [1]={
      args="(int link_id)",
      argsT={
        [1]={
          name="link_id",
          type="int"}},
      argsoriginal="(int link_id)",
      call_args="(link_id)",
      cimguiname="ImNodes_SelectLink",
      defaults={},
      funcname="SelectLink",
      location="imnodes:335",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SelectLink",
      ret="void",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_SelectNode={
    [1]={
      args="(int node_id)",
      argsT={
        [1]={
          name="node_id",
          type="int"}},
      argsoriginal="(int node_id)",
      call_args="(node_id)",
      cimguiname="ImNodes_SelectNode",
      defaults={},
      funcname="SelectNode",
      location="imnodes:332",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SelectNode",
      ret="void",
      signature="(int)",
      stname=""},
    ["(int)"]=nil},
  ImNodes_SetCurrentContext={
    [1]={
      args="(ImNodesContext* ctx)",
      argsT={
        [1]={
          name="ctx",
          type="ImNodesContext*"}},
      argsoriginal="(ImNodesContext* ctx)",
      call_args="(ctx)",
      cimguiname="ImNodes_SetCurrentContext",
      defaults={},
      funcname="SetCurrentContext",
      location="imnodes:205",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SetCurrentContext",
      ret="void",
      signature="(ImNodesContext*)",
      stname=""},
    ["(ImNodesContext*)"]=nil},
  ImNodes_SetImGuiContext={
    [1]={
      args="(ImGuiContext* ctx)",
      argsT={
        [1]={
          name="ctx",
          type="ImGuiContext*"}},
      argsoriginal="(ImGuiContext* ctx)",
      call_args="(ctx)",
      cimguiname="ImNodes_SetImGuiContext",
      defaults={},
      funcname="SetImGuiContext",
      location="imnodes:200",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SetImGuiContext",
      ret="void",
      signature="(ImGuiContext*)",
      stname=""},
    ["(ImGuiContext*)"]=nil},
  ImNodes_SetNodeDraggable={
    [1]={
      args="(int node_id,const bool draggable)",
      argsT={
        [1]={
          name="node_id",
          type="int"},
        [2]={
          name="draggable",
          type="const bool"}},
      argsoriginal="(int node_id,const bool draggable)",
      call_args="(node_id,draggable)",
      cimguiname="ImNodes_SetNodeDraggable",
      defaults={},
      funcname="SetNodeDraggable",
      location="imnodes:285",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SetNodeDraggable",
      ret="void",
      signature="(int,const bool)",
      stname=""},
    ["(int,const bool)"]=nil},
  ImNodes_SetNodeEditorSpacePos={
    [1]={
      args="(int node_id,const ImVec2 editor_space_pos)",
      argsT={
        [1]={
          name="node_id",
          type="int"},
        [2]={
          name="editor_space_pos",
          type="const ImVec2"}},
      argsoriginal="(int node_id,const ImVec2& editor_space_pos)",
      call_args="(node_id,editor_space_pos)",
      cimguiname="ImNodes_SetNodeEditorSpacePos",
      defaults={},
      funcname="SetNodeEditorSpacePos",
      location="imnodes:297",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SetNodeEditorSpacePos",
      ret="void",
      signature="(int,const ImVec2)",
      stname=""},
    ["(int,const ImVec2)"]=nil},
  ImNodes_SetNodeGridSpacePos={
    [1]={
      args="(int node_id,const ImVec2 grid_pos)",
      argsT={
        [1]={
          name="node_id",
          type="int"},
        [2]={
          name="grid_pos",
          type="const ImVec2"}},
      argsoriginal="(int node_id,const ImVec2& grid_pos)",
      call_args="(node_id,grid_pos)",
      cimguiname="ImNodes_SetNodeGridSpacePos",
      defaults={},
      funcname="SetNodeGridSpacePos",
      location="imnodes:298",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SetNodeGridSpacePos",
      ret="void",
      signature="(int,const ImVec2)",
      stname=""},
    ["(int,const ImVec2)"]=nil},
  ImNodes_SetNodeScreenSpacePos={
    [1]={
      args="(int node_id,const ImVec2 screen_space_pos)",
      argsT={
        [1]={
          name="node_id",
          type="int"},
        [2]={
          name="screen_space_pos",
          type="const ImVec2"}},
      argsoriginal="(int node_id,const ImVec2& screen_space_pos)",
      call_args="(node_id,screen_space_pos)",
      cimguiname="ImNodes_SetNodeScreenSpacePos",
      defaults={},
      funcname="SetNodeScreenSpacePos",
      location="imnodes:296",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_SetNodeScreenSpacePos",
      ret="void",
      signature="(int,const ImVec2)",
      stname=""},
    ["(int,const ImVec2)"]=nil},
  ImNodes_StyleColorsClassic={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_StyleColorsClassic",
      defaults={},
      funcname="StyleColorsClassic",
      location="imnodes:220",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_StyleColorsClassic",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_StyleColorsDark={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_StyleColorsDark",
      defaults={},
      funcname="StyleColorsDark",
      location="imnodes:219",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_StyleColorsDark",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  ImNodes_StyleColorsLight={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="ImNodes_StyleColorsLight",
      defaults={},
      funcname="StyleColorsLight",
      location="imnodes:221",
      namespace="ImNodes",
      ov_cimguiname="ImNodes_StyleColorsLight",
      ret="void",
      signature="()",
      stname=""},
    ["()"]=nil},
  LinkDetachWithModifierClick_LinkDetachWithModifierClick={
    [1]={
      args="()",
      argsT={},
      argsoriginal="()",
      call_args="()",
      cimguiname="LinkDetachWithModifierClick_LinkDetachWithModifierClick",
      constructor=true,
      defaults={},
      funcname="LinkDetachWithModifierClick",
      location="imnodes:110",
      ov_cimguiname="LinkDetachWithModifierClick_LinkDetachWithModifierClick",
      signature="()",
      stname="LinkDetachWithModifierClick"},
    ["()"]=nil},
  LinkDetachWithModifierClick_destroy={
    [1]={
      args="(LinkDetachWithModifierClick* self)",
      argsT={
        [1]={
          name="self",
          type="LinkDetachWithModifierClick*"}},
      call_args="(self)",
      cimguiname="LinkDetachWithModifierClick_destroy",
      defaults={},
      destructor=true,
      location="imnodes:110",
      ov_cimguiname="LinkDetachWithModifierClick_destroy",
      ret="void",
      signature="(LinkDetachWithModifierClick*)",
      stname="LinkDetachWithModifierClick"},
    ["(LinkDetachWithModifierClick*)"]=nil}}
t.EmulateThreeButtonMouse_EmulateThreeButtonMouse["()"]=t.EmulateThreeButtonMouse_EmulateThreeButtonMouse[1]
t.EmulateThreeButtonMouse_destroy["(EmulateThreeButtonMouse*)"]=t.EmulateThreeButtonMouse_destroy[1]
t.ImNodesIO_ImNodesIO["()"]=t.ImNodesIO_ImNodesIO[1]
t.ImNodesIO_destroy["(ImNodesIO*)"]=t.ImNodesIO_destroy[1]
t.ImNodesStyle_ImNodesStyle["()"]=t.ImNodesStyle_ImNodesStyle[1]
t.ImNodesStyle_destroy["(ImNodesStyle*)"]=t.ImNodesStyle_destroy[1]
t.ImNodes_BeginInputAttribute["(int,ImNodesPinShape)"]=t.ImNodes_BeginInputAttribute[1]
t.ImNodes_BeginNode["(int)"]=t.ImNodes_BeginNode[1]
t.ImNodes_BeginNodeEditor["()"]=t.ImNodes_BeginNodeEditor[1]
t.ImNodes_BeginNodeTitleBar["()"]=t.ImNodes_BeginNodeTitleBar[1]
t.ImNodes_BeginOutputAttribute["(int,ImNodesPinShape)"]=t.ImNodes_BeginOutputAttribute[1]
t.ImNodes_BeginStaticAttribute["(int)"]=t.ImNodes_BeginStaticAttribute[1]
t.ImNodes_ClearLinkSelection["()"]=t.ImNodes_ClearLinkSelection[1]
t.ImNodes_ClearLinkSelection["(int)"]=t.ImNodes_ClearLinkSelection[2]
t.ImNodes_ClearNodeSelection["()"]=t.ImNodes_ClearNodeSelection[1]
t.ImNodes_ClearNodeSelection["(int)"]=t.ImNodes_ClearNodeSelection[2]
t.ImNodes_CreateContext["()"]=t.ImNodes_CreateContext[1]
t.ImNodes_DestroyContext["(ImNodesContext*)"]=t.ImNodes_DestroyContext[1]
t.ImNodes_EditorContextCreate["()"]=t.ImNodes_EditorContextCreate[1]
t.ImNodes_EditorContextFree["(ImNodesEditorContext*)"]=t.ImNodes_EditorContextFree[1]
t.ImNodes_EditorContextGetPanning["()"]=t.ImNodes_EditorContextGetPanning[1]
t.ImNodes_EditorContextMoveToNode["(const int)"]=t.ImNodes_EditorContextMoveToNode[1]
t.ImNodes_EditorContextResetPanning["(const ImVec2)"]=t.ImNodes_EditorContextResetPanning[1]
t.ImNodes_EditorContextSet["(ImNodesEditorContext*)"]=t.ImNodes_EditorContextSet[1]
t.ImNodes_EndInputAttribute["()"]=t.ImNodes_EndInputAttribute[1]
t.ImNodes_EndNode["()"]=t.ImNodes_EndNode[1]
t.ImNodes_EndNodeEditor["()"]=t.ImNodes_EndNodeEditor[1]
t.ImNodes_EndNodeTitleBar["()"]=t.ImNodes_EndNodeTitleBar[1]
t.ImNodes_EndOutputAttribute["()"]=t.ImNodes_EndOutputAttribute[1]
t.ImNodes_EndStaticAttribute["()"]=t.ImNodes_EndStaticAttribute[1]
t.ImNodes_GetCurrentContext["()"]=t.ImNodes_GetCurrentContext[1]
t.ImNodes_GetIO["()"]=t.ImNodes_GetIO[1]
t.ImNodes_GetNodeDimensions["(int)"]=t.ImNodes_GetNodeDimensions[1]
t.ImNodes_GetNodeEditorSpacePos["(const int)"]=t.ImNodes_GetNodeEditorSpacePos[1]
t.ImNodes_GetNodeGridSpacePos["(const int)"]=t.ImNodes_GetNodeGridSpacePos[1]
t.ImNodes_GetNodeScreenSpacePos["(const int)"]=t.ImNodes_GetNodeScreenSpacePos[1]
t.ImNodes_GetSelectedLinks["(int*)"]=t.ImNodes_GetSelectedLinks[1]
t.ImNodes_GetSelectedNodes["(int*)"]=t.ImNodes_GetSelectedNodes[1]
t.ImNodes_GetStyle["()"]=t.ImNodes_GetStyle[1]
t.ImNodes_IsAnyAttributeActive["(int*)"]=t.ImNodes_IsAnyAttributeActive[1]
t.ImNodes_IsAttributeActive["()"]=t.ImNodes_IsAttributeActive[1]
t.ImNodes_IsEditorHovered["()"]=t.ImNodes_IsEditorHovered[1]
t.ImNodes_IsLinkCreated["(int*,int*,bool*)"]=t.ImNodes_IsLinkCreated[1]
t.ImNodes_IsLinkCreated["(int*,int*,int*,int*,bool*)"]=t.ImNodes_IsLinkCreated[2]
t.ImNodes_IsLinkDestroyed["(int*)"]=t.ImNodes_IsLinkDestroyed[1]
t.ImNodes_IsLinkDropped["(int*,bool)"]=t.ImNodes_IsLinkDropped[1]
t.ImNodes_IsLinkHovered["(int*)"]=t.ImNodes_IsLinkHovered[1]
t.ImNodes_IsLinkSelected["(int)"]=t.ImNodes_IsLinkSelected[1]
t.ImNodes_IsLinkStarted["(int*)"]=t.ImNodes_IsLinkStarted[1]
t.ImNodes_IsNodeHovered["(int*)"]=t.ImNodes_IsNodeHovered[1]
t.ImNodes_IsNodeSelected["(int)"]=t.ImNodes_IsNodeSelected[1]
t.ImNodes_IsPinHovered["(int*)"]=t.ImNodes_IsPinHovered[1]
t.ImNodes_Link["(int,int,int)"]=t.ImNodes_Link[1]
t.ImNodes_LoadCurrentEditorStateFromIniFile["(const char*)"]=t.ImNodes_LoadCurrentEditorStateFromIniFile[1]
t.ImNodes_LoadCurrentEditorStateFromIniString["(const char*,size_t)"]=t.ImNodes_LoadCurrentEditorStateFromIniString[1]
t.ImNodes_LoadEditorStateFromIniFile["(ImNodesEditorContext*,const char*)"]=t.ImNodes_LoadEditorStateFromIniFile[1]
t.ImNodes_LoadEditorStateFromIniString["(ImNodesEditorContext*,const char*,size_t)"]=t.ImNodes_LoadEditorStateFromIniString[1]
t.ImNodes_MiniMap["(const float,const ImNodesMiniMapLocation,const ImNodesMiniMapNodeHoveringCallback,void*)"]=t.ImNodes_MiniMap[1]
t.ImNodes_NumSelectedLinks["()"]=t.ImNodes_NumSelectedLinks[1]
t.ImNodes_NumSelectedNodes["()"]=t.ImNodes_NumSelectedNodes[1]
t.ImNodes_PopAttributeFlag["()"]=t.ImNodes_PopAttributeFlag[1]
t.ImNodes_PopColorStyle["()"]=t.ImNodes_PopColorStyle[1]
t.ImNodes_PopStyleVar["()"]=t.ImNodes_PopStyleVar[1]
t.ImNodes_PushAttributeFlag["(ImNodesAttributeFlags)"]=t.ImNodes_PushAttributeFlag[1]
t.ImNodes_PushColorStyle["(ImNodesCol,unsigned int)"]=t.ImNodes_PushColorStyle[1]
t.ImNodes_PushStyleVar["(ImNodesStyleVar,float)"]=t.ImNodes_PushStyleVar[1]
t.ImNodes_SaveCurrentEditorStateToIniFile["(const char*)"]=t.ImNodes_SaveCurrentEditorStateToIniFile[1]
t.ImNodes_SaveCurrentEditorStateToIniString["(size_t*)"]=t.ImNodes_SaveCurrentEditorStateToIniString[1]
t.ImNodes_SaveEditorStateToIniFile["(const ImNodesEditorContext*,const char*)"]=t.ImNodes_SaveEditorStateToIniFile[1]
t.ImNodes_SaveEditorStateToIniString["(const ImNodesEditorContext*,size_t*)"]=t.ImNodes_SaveEditorStateToIniString[1]
t.ImNodes_SelectLink["(int)"]=t.ImNodes_SelectLink[1]
t.ImNodes_SelectNode["(int)"]=t.ImNodes_SelectNode[1]
t.ImNodes_SetCurrentContext["(ImNodesContext*)"]=t.ImNodes_SetCurrentContext[1]
t.ImNodes_SetImGuiContext["(ImGuiContext*)"]=t.ImNodes_SetImGuiContext[1]
t.ImNodes_SetNodeDraggable["(int,const bool)"]=t.ImNodes_SetNodeDraggable[1]
t.ImNodes_SetNodeEditorSpacePos["(int,const ImVec2)"]=t.ImNodes_SetNodeEditorSpacePos[1]
t.ImNodes_SetNodeGridSpacePos["(int,const ImVec2)"]=t.ImNodes_SetNodeGridSpacePos[1]
t.ImNodes_SetNodeScreenSpacePos["(int,const ImVec2)"]=t.ImNodes_SetNodeScreenSpacePos[1]
t.ImNodes_StyleColorsClassic["()"]=t.ImNodes_StyleColorsClassic[1]
t.ImNodes_StyleColorsDark["()"]=t.ImNodes_StyleColorsDark[1]
t.ImNodes_StyleColorsLight["()"]=t.ImNodes_StyleColorsLight[1]
t.LinkDetachWithModifierClick_LinkDetachWithModifierClick["()"]=t.LinkDetachWithModifierClick_LinkDetachWithModifierClick[1]
t.LinkDetachWithModifierClick_destroy["(LinkDetachWithModifierClick*)"]=t.LinkDetachWithModifierClick_destroy[1]
 return t